### ISSUE TITLE
Certificate updating script

### ISSUE THREAD

**Issue by norling** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#18]
To ensure that certificates stay updated in the containers when they are renewed by certbot, we need a script that copies the renewed certificates to a certificate docker volume. This script is intended to be run using the `certbot renew --post-hook`.

The script should:
 - [x] copy certificates from a source directory to a named docker volume
 - [x] ensure that the copied certificates have correct permissions 
 - [x] restart any running docker containers that have the volume mounted

**Comment by andkaha** [comment]
We will use `--deploy-hook` rather than `--post-hook`.  The former is executed once on successful renewal, while the latter is executed on every _attempt_ to renew a certificate.
