### ISSUE TITLE
Scripts for ingestion process

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#2]
As a GDI developer
I want to have well documented scripts for the ingestion process
In order to be able to add files and datasets in the archive and understand the whole process behind it

A/C
- One script for each step of the ingestion process. Something along the lines of:

```sh 
$ sda-cli upload [...] <file>
$ ingest.sh <file> [<file>...]
$ set_file_accession.sh <file> <accession>
$ map_files_to_dataset.sh <dataset> <accession> [<accession>...]
```

[sda-dashboard bootstrap script](https://github.com/neicnordic/sda-dashboard/blob/main/dev_utils/scripts/bootstrap.sh)

There's a dependency between the scripts on things happening in the archive, which can take a long time. So some check that it's ok to continue needs to be there.

Use the docker-compose provided in the GenomicDataInfrastructure/starter-kit-storage-and-interfaces repository.

**Comment by andkaha** [comment]
The preliminary command synopsis:

```
sda SUBCOMMAND [OPTION...] [OPERAND...]
```

For example,

```
sda upload filepath [filepath...]    # upload a bunch of files

sda ingest filepath [filepath...]    # ingest a bunch of uploaded files

sda accession filepath accession-id     # set accession of a file
sda accession filepath                  # get accession of a file

# set (append with -a) accessions to a dataset
# ... by file path with -f
sda dataset [-a] dataset-id accession-id [accession-id...]
sda dataset [-a] -f dataset-id filepath [filepath...]

# get accesions (file paths with -f) given a dataset
sda dataset dataset-id
sda dataset -f dataset-id
```

Or something similar.
