### ISSUE TITLE
starter-kit-storage-and-interfaces stuck at startup 

### ISSUE THREAD

**Issue by hcvdwerf** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#28]
When I run docker compose -f docker-compose-demo.yml up -d  the OIDC tries to starts up, but it takes infinite time. I changed all settings just as described in the repo.  What is happening here? 

<img width="1048" alt="Screenshot 2023-06-08 at 22 17 11" src="https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/assets/26299191/3a3c4202-4a18-49df-95ac-1b9ffcf9e3ad">

**Comment by andkaha** [comment]
Hi there!

Could you let me know what checkout you are using right now? The most recent commit on `main` is from a few moments ago, and there were changes made to the `main` branch last week that might have fixed a similar issue that @aaperis and I found.

If you update your checked-out repository and try again, does it work for you?  If not, could you share relevant parts of the container logs?

**Comment by aaperis** [comment]
Hi @hcvdwerf , as @kusalananda mentioned please try again with an updated version of the repository and post some container logs.

As a small remark, I noticed that you are running `docker-compose-demo.yml` however this does not need any changes to be made. Please try running `docker-compose.yml` instead, if your goal is to run the full stack along with `ls-aai-mock`.

**Comment by hcvdwerf** [comment]
Thanks for you quick reply! Pulling the latest version solved the problem. Thanks!
