### ISSUE TITLE
Fix script for renewal

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#30]
The script for renewal of the certificates is failing somehow, making the certificates not accessible from the services (permission denied). We fixed the issue temporarily (manually), however, the `cert-deploy` script needs to be updated and tested

**Comment by andkaha** [comment]
Was this resolved by https://github.com/NBISweden/LocalEGA-SE-Deployment/pull/667 ?
