### ISSUE TITLE
Update `sda-admin` script

### ISSUE THREAD

**Issue by aaperis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#33]
The `scripts/sda-admin` script needs to be updated to reflect changes done during deployment in the VM. Most of these changes  already exist in the branch [cert-script-cleanup](https://github.com/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/tree/todo/cert-script-cleanup).

This should include the relevant documentation.

**Comment by andkaha** [comment]
The `todo/cert-script-cleanup` branch was merged into the `todo/sda-admin-updates` branch on the 7th of June. _That_ branch was merged into `main` on the 12th of June.

**Comment by aaperis** [comment]
@kusalananda my bad, `todo/sda-admin-updates` is deleted whereas `todo/cert-script-cleanup` isn't and that confused me.

**Comment by andkaha** [comment]
I'll delete that branch now unless it's been deleted already. I tend to delete merged branches, and I don't know why this wasn't.

**Comment by aaperis** [comment]
This was a false alarm, matter is resolved so I am closing the issue.
