### ISSUE TITLE
sda-admin behaves differently when ingesting folders depending on trailing `/`

### ISSUE THREAD

**Issue by aaperis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#35]
Given a correctly encrypted file `test_file.c4gh` but uploaded to a target folder, <folder>, without its *.c4gh extension `sda-admin` fails to ingest as follows:

```
s3cmd -c s3cmd.conf put test_file.c4gh s3://jd123_lifescience-ri.eu/bams/test2_file.bam
```

These fail:
```
./scripts/sda-admin ingest bams
./scripts/sda-admin ingest bams/test2_file.bam
```

This works:
```
./scripts/sda-admin ingest bams/
```

What makes the difference is the trailing `/`.

**Comment by andkaha** [comment]
The trailing `/` makes the `ingest` action treat the argument as a directory and will ingest all files beneath that path.  Without the trailing `/`, the `ingest` action will assume the argument is a file and will try to add `.c4gh` to the end of it to match it against a name in the user's storage bucket.

See also the help text that you get from
```
./scripts/sda-admin help ingest
```


```
The "ingest" sub-command is used for ingesting one or several
uploaded files.

Filenames do not have to be given with the trailing ".c4gh"
filename suffix.

If a directory path is specified with a trailing slash, all
files in or beneath that directory will be ingested recursively.
Specifying an empty string ("") as the pathname will have the
effect of ingesting all files in the user's inbox.

Example usage:

    Listing the filenames currently in the "inbox" queue waiting
    to be ingested:

    ./sda-admin ingest

    Files may be ingested one by one or several at once.
    Ingesting three files:

    ./sda-admin ingest file1 file2
    ./sda-admin ingest file3

    Ingesting all files in or beneath the "project/data" path:

    ./sda-admin ingest project/data/
```

**Comment by andkaha** [comment]
Also note that we decided that all uploaded files must be encrypted and have the `.c4gh` filename suffix.  I think this is why your ingestion command fails; there is no file in the bucket called `bams/test2_file.bam.c4gh`.

With `sda-admin ingest bams/` _all_ files under `bams` are ingested, no matter what their names are, which could be considered a bug, I suppose, as we should only ingest files that have the correct filename suffix.
