### ISSUE TITLE
Update images to work with htsget-rs

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#47]
As an gdi-dev
I want to have the latest images from the sensitive data archive, including the re-encrypt service
In order to be able to work with the htsget-rs new version

Tasks:
- [ ] Update the images in the storage and interfaces repo
- [ ] Update the image or htsget-rs in the htsget repo
- [ ] Make sure they work together, by requesting an encrypted file via htsget

**Comment by MalinAhlberg** [comment]
`feat/htsget-crypt4gh` now contains new images of the `sda`s. It includes the re-encryption and implements the start coordinate for byte ranges. The `download` is wip, though.
It's tested with htsget (using [feature/rust-htsget](https://github.com/GenomicDataInfrastructure/starter-kit-htsget/tree/feature/rust-htsget)), by requesting encrypted data. Note that there is still one or two bugs in htsget.
