### ISSUE TITLE
Quickstart documentation for the SDA

### ISSUE THREAD

**Issue by norling** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#6]
We need documentation for the new GDI users who are unused to working with the SDA.

Primary goal of the documentation are the vanguardnodes that have no previous experience and they need to set it up by June.

Documentation should include:
 - Adding letsencrypt certificates to internet facing services
 - Link to the SDA documentation
 - How to perform common tasks for users (uploading, and downloading)
 - How to perform common tasks for admins (ingesting, adding accession IDs, mapping to datasets, checking status of services, working with rabbitmq, etc.)
 - Authentication for users (mock or AAI)
 - Links to explanations about visas and rems

**Comment by jbygdell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Giant-Sloth-6041ec3fd9297d0016321f73/issues/GenomicDataInfrastructure/starter-kit-storage-and-interfaces/6?planning-poker) with Zenhub @dbampalikis @kusalananda @norling
